import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button } from "@mui/material";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [message, setMessage] = useState("");
  useEffect(() => {
    fetch("./api/hello")
      .then((res: Response) => res.json())
      .then((data) => setMessage(data.name));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="outlined">{message}</Button>
    </div>
  );
};

export default Home;
